export {
    Avatar,
    AvatarImage,
    AvatarFallback,
    AvatarText,
    AvatarBadge,
    AvatarIcon,
    AvatarGroup,
    AvatarGroupCount,
    type AvatarProps,
    type AvatarSize,
    type AvatarColor,
    type AvatarColorIcon,
    type AvatarColorImage,
    type AvatarColorInitials,
    type AvatarLayout,
    type AvatarImageProps,
    type AvatarFallbackProps,
    type AvatarTextProps,
    type AvatarBadgeProps,
    type AvatarIconProps,
    type AvatarGroupProps,
    type AvatarGroupCountProps,
    type AvatarPresenceStatus,
} from "./Avatar";
