export {
    footerLinkClassName,
    footerLocaleLinkClassName,
    footerLocaleTriggerClassName,
    footerSocialLinkClassName,
    Footer,
    FooterBottom,
    FooterBrand,
    FooterBrandDescription,
    FooterBrandName,
    FooterContent,
    FooterCopyright,
    FooterGroup,
    FooterGroupLabel,
    FooterLink,
    FooterLocale,
    FooterLogo,
    FooterNav,
    FooterSocial,
} from "./Footer";
export type {
    FooterBottomProps,
    FooterBrandDescriptionProps,
    FooterBrandNameProps,
    FooterBrandProps,
    FooterContentProps,
    FooterCopyrightProps,
    FooterGroupLabelProps,
    FooterGroupProps,
    FooterLinkProps,
    FooterLocaleProps,
    FooterLogoProps,
    FooterNavProps,
    FooterProps,
    FooterSocialProps,
} from "./types";
